version: '3.8'
services:
  db_nodo1:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: datos_principales
      POSTGRES_USER: user_bddd
      POSTGRES_PASSWORD: superclave
    ports:
      - "5432:5432"
    volumes:
      - nodo1_data:/var/lib/postgresql/data
    healthcheck: # <-- AÑADIR ESTO
      test: ["CMD-SHELL", "pg_isready -U user_bddd -d datos_principales"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_nodo2:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: datos_secundarios
      POSTGRES_USER: user_bddd
      POSTGRES_PASSWORD: superclave
    ports:
      - "5433:5432"
    volumes:
      - nodo2_data:/var/lib/postgresql/data
    healthcheck: # <-- AÑADIR ESTO
      test: ["CMD-SHELL", "pg_isready -U user_bddd -d datos_secundarios"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend_server:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: bddd_backend
    ports:
      - "8080:8080"
    environment:
      DB1_HOST: db_nodo1
      DB2_HOST: db_nodo2
      DB_USER: user_bddd
      DB_PASS: superclave
    depends_on: # <-- MODIFICAR ESTO
      db_nodo1:
        condition: service_healthy
      db_nodo2:
        condition: service_healthy

volumes:
  nodo1_data:
  nodo2_data: